/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package hqt_csdl;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xuanb
 */
public class CTHoaDon extends javax.swing.JDialog {

    private ConSQL conn = new ConSQL();
    private String[] columns_chitiet_hd = {"", "Sach", "SoLuong", "DonGia", "Tong"};

    /**
     * Creates new form CTHoaDon
     */
    public CTHoaDon(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        LoadDataIntoTableCTHoaDon();
    }

    public void LoadDataIntoTableCTHoaDon() {
    try {
        // Tạo mô hình bảng
        DefaultTableModel model = new DefaultTableModel(columns_chitiet_hd, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                // Chỉ cho phép chỉnh sửa cột "Số lượng"
                return column == 0 || column == 2;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                // Cột 0 chứa checkbox
                if (columnIndex == 0) {
                    return Boolean.class;
                }
                return String.class;
            }
        };

        // Lấy dữ liệu từ cơ sở dữ liệu
        ResultSet rs = conn.GetSach();
        while (rs.next()) {
            Sach s = new Sach(rs.getInt(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getDouble(6), rs.getInt(7));
            Object[] row = {
                false,            // Checkbox
                s.getTieuDe(),    // Tiêu đề sách
                0,                // Số lượng (ban đầu là 0)
                s.getGia(),       // Đơn giá
                0.0               // Thành tiền (ban đầu là 0)
            };
            model.addRow(row);
        }

        // Lắng nghe sự thay đổi trong bảng
        model.addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                // Xử lý sự kiện chỉ khi cột "Số lượng" (index = 2) thay đổi
                if (e.getColumn() == 2) {
                    int row = e.getFirstRow(); // Hàng được thay đổi
                    if (row != -1) {
                        try {
                            // Lấy số lượng và đơn giá
                            int SL = Integer.parseInt(model.getValueAt(row, 2).toString());
                            double DG = Double.parseDouble(model.getValueAt(row, 3).toString());
                            
                            // Tính thành tiền
                            double total = SL * DG;
                            model.setValueAt(total, row, 4); // Cập nhật cột "Thành tiền"
                        } catch (NumberFormatException ex) {
                            JOptionPane.showMessageDialog(null, "Số lượng phải là số nguyên!", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
                            model.setValueAt(0, row, 4); // Nếu lỗi, đặt "Thành tiền" về 0
                        }
                    }
                }
            }
        });

        // Thiết lập mô hình cho bảng
        CTHoaDon_table.setModel(model);

    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Xảy ra lỗi khi kết nối CSDL", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        CTHoaDon_table = new javax.swing.JTable();
        HoanTat_btn = new javax.swing.JButton();
        Dong_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("CHI TIẾT HÓA ĐƠN");

        CTHoaDon_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        CTHoaDon_table.setColumnSelectionAllowed(true);
        CTHoaDon_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        CTHoaDon_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        CTHoaDon_table.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                CTHoaDon_tablePropertyChange(evt);
            }
        });
        jScrollPane6.setViewportView(CTHoaDon_table);

        HoanTat_btn.setText("Hoàn Tất");
        HoanTat_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoanTat_btnActionPerformed(evt);
            }
        });

        Dong_btn.setText("Đóng");
        Dong_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dong_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(HoanTat_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174)
                .addComponent(Dong_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Dong_btn, HoanTat_btn});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoanTat_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dong_btn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Dong_btn, HoanTat_btn});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CTHoaDon_tablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_CTHoaDon_tablePropertyChange

    }//GEN-LAST:event_CTHoaDon_tablePropertyChange

    private void HoanTat_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoanTat_btnActionPerformed
        
    }//GEN-LAST:event_HoanTat_btnActionPerformed

    private void Dong_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dong_btnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Dong_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CTHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CTHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CTHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CTHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CTHoaDon dialog = new CTHoaDon(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CTHoaDon_table;
    private javax.swing.JButton Dong_btn;
    private javax.swing.JButton HoanTat_btn;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
